version: '3'
services:
  eureka-server:
    build: .
    ports:
      - "8761:8761"
    environment:
      - SPRING_PROFILES_ACTIVE=docker
    networks:
      - exchange-network
    healthcheck:
      test: ["CMD", "wget", "--quiet", "--tries=1", "--spider", "http://localhost:8761/actuator/health"]
      interval: 30s
      timeout: 3s
      retries: 3
    restart: unless-stopped

networks:
  exchange-network:
    driver: bridge
